# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('ip_addr', models.GenericIPAddressField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish')),
            ],
        ),
    ]
